### ISSUE TITLE
Change pancake recipe

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#171]
To not use crafting table

**Comment by jasperalani** [comment]
This has been done.

**Comment by Yarden-zamir** [comment]
The current recipe is still a crafting table recipe just done in the mixer it seems. I think a better solution would be an assembly recipe with dough

**Comment by Yarden-zamir** [comment]
Any recipe that involves a phisical bucket should probably be converted to a pouring or assembly recipe
