### ISSUE TITLE
remove botania making functional flower advancement Electric magic

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#235]

**Comment by jasperalani** [comment]
sorry can you explain a bit more lmao

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1198429263582461963/1198500245114466354) 
> there is an advancement from botania for making flowers which you get when getting a flower from a trade here which is weird. it just popped out as anoyying but all the advancements were removed since then I think so it's fine

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1198429263582461963/1198738613287010396) 
> ok cool

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1198429263582461963/1198738632236867764) 
> thanks for explaining
