### ISSUE TITLE
Rename quartz to nether quarts and change texture to use ae2's cirtus quartz as it looks better 

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#236]

**Comment by jasperalani** [comment]
is this for vanilla quartz or ae2 quarts? seems this does not apply anymore

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1198429621872504852/1198499686986817567) 
> ah think I've done that already, vanilla quartz

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1198429621872504852/1198499885863931944) 
> on I've done the rename, not the retexture

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1198429621872504852/1198499923260342352) 
> not sure about the retexture though

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1198429621872504852/1198738360857006090) 
> there is no cirtus quartz anyway
