### ISSUE TITLE
Add a fence to the spaceship somewhere

### ISSUE THREAD

**Issue by TulkinRB** [game-design-driven/Create-Prepare-to-Dye#336]
So people can tie Betsy's lead somewhere early game

**Comment by Yarden-zamir** [comment]
Are there none wood fences?

**Comment by TulkinRB** [comment]
Unfortunately not :(

There are stone walls, but I think you can't tie leads to them. As for metal there are none.

I thought about making create's girder stuff work with leads but for now we can add a fence

**Comment by Yarden-zamir** [comment]
I think if it's a fence type it should be automatic, look at how to make a fence in kjs and I expect it will work out of the box

**Comment by Yarden-zamir** [comment]
Now that we have a fence, this should be a thing

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1194714238074236998) 
> I'll do it when I update the ship with the new crates

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1194765858497634366) 
> awesome

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196415030439198740) 
> I'm not sure the modpack itself has the new mod version tho looking at the main repos PRs

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196416130466713610) 
> Oh, I don't see an open pr to update though

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196416392627486740) 
> They were all closed by Kiki

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196416576065392701) 
> [kikis2111](https://discord.com/channels/890222432605057044/1193494483522818059/1196416576065392701) is the latest version broken or something?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196416738405912596) 
> In general the auto pr is built on the assumption that main always runs so if you have something incomplete a branch is a better place for it

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196417233870659634) 
> I think there's an issue with version names updating on push in branches. Since each time I did a push it would increment the version

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196417457276067850) 
> Ah, maybe the ci runs on all branches partially? I'll take a look, thought I filtered for main

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196417681180590141) 
> *I may of forgot to make my own branches, so I meant fork more so. I pushed to main on my fork which updated the version. That probably broke things*

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196417865276985495) 
> https://github.com/EngineerSmith/ptdye-plus/commits/main/
Like half of these were merge fixes lmao and then as I didn't pull. It wanted more merges

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196425617877516399) 
> o

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196425733623513098) 
> i thought forks dont have the original ci

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196513503473827841) 
> yeah there is something going wrong with the ci task, fixing it now then will make sure engineers code is included in the latest pr

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196515258131550308) 
> dont approve any version update pr's  for now yarden

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196529419834101812) 
> [engineersmith_4628](https://discord.com/channels/890222432605057044/1193494483522818059/1196529419834101812) can you disable the workflow on your fork

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196529500939354174) 
> it should be disabled by default

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196530005916790916) 
> testing your code now engin

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196530206400327720) 
> Disabled 👍

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196533817100476586) 
> cool

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196533876332437625) 
> [yarden.zamir](https://discord.com/channels/890222432605057044/1193494483522818059/1196533876332437625) seems to be a problem with curseforge approving the files for release

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196533954442969118) 
> so the when the pr task runs it runs packwiz update curseforge but the latest release hasnt been approved

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534662177230888) 
> oh lol, that makes sense

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534670066712576) 
> so having to manually update the curseforge files

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534683635290184) 
> each time

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534690052591727) 
> hm

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534718125047858) 
> need a timer

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534754514849792) 
> like wait 30mins then run packwiz update

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534820986159115) 
> sure, add a few minutes sleep to the cf one

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196534940372844756) 
> but add a cuncurency group cancel, so if more jobs come the old ones get canceled

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196535044668391474) 
> dont remember the exact terminology

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196535125287116820) 
> hm ok

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196548456278401025) 
> latest pr is ready to go yarden

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1193494483522818059/1196549022312321145) 
> if a job is cancelled somewhere in the middle
