### ISSUE TITLE
Add pondering on blocks the player looks at

### ISSUE THREAD

**Issue by TulkinRB** [game-design-driven/Create-Prepare-to-Dye#354]

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190068791758041229/1193494865728782421) 
>

**Comment by EngineerSmith** [comment]
As this is added with ptdye-plus (despite it's bugs) I'll close it.
