### ISSUE TITLE
figure out an intuitive solution for server file distibution

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#380]

**Comment by EngineerSmith** [comment]
I think the current system covers this issue - reopen if it doesn't

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1202305065348767834/1206515791365935124) 
> The current solution doenst cover curseforge, so its not good enough, we need to also figure out cureseforge dist for server

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1202305065348767834/1206516096249888800) 
> But we can move to [Figure out server file automation for curseforge](https://discord.com/channels/890222432605057044/1190271648411172874) for that
