### ISSUE TITLE
remove smoker from game

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#420]

**Comment by Yarden-zamir** [comment]
Anyone want's to take this on?

**Comment by EngineerSmith** [comment]
This has been removed from what I can tell - it's been tooltipped as removed. So I'm closing this issue
![image](https://github.com/game-design-driven/Create-Prepare-to-Dye/assets/56016593/5e87fdd9-0d3d-4938-afe3-7bf851929d6f)
