### ISSUE TITLE
make at least two colors of smart cable be part of the ae2 device

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#465]
this is both nice for backwards compat with the light blue cables, and allows for some decoration and cable shenanigans that wouldn't otherwise be available.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192216672673738762) 
> Agreed. Since you are not the one crafting them we can assume they are smart enough to change colors and let you change all of them

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192232750309195806) 
> wait I should ping pending code contributors maybe...

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192232897093046504) 
> i don't seem to have permission for that but it might just be mobiles bad ui

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192234201492226119) 
> Everyone has permission for pings here i think

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192234383210467418) 
> <@&1181024760730226708> if anyone wants to add the colored versions of me cables to the network devices that could be a nice first contribution

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192234637158781051) 
> the file is kubejs/server_scripts/base/featrues/devices.js

**Comment by Eastwomc14** [comment]
I might if I have time after school...

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192241919103881356) 
> should they all be accessible?

**Comment by Eastwomc14** [comment]
Yes

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192242145575305226) 
> i think there's an argument to be made to keep the color pool low so there's a consistent asthetic

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192242750440095914) 
> a facade could also be nice, like one for a specific block

**Comment by TheFarawayDev** [comment]
So fake blocks for the cables?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192242887623180379) 
> im pretty sure you can't get the blocks back out of a facade in any way so it should be safe to make it part of the device

**Comment by TheFarawayDev** [comment]
**NOTES:**
- Wants Facade
- New Color Cables

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192243794016473248) 
> hm.. maybe. but it will feel wierd to have some colores a device and some manual. I think we should either have them all or have the others removed

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192244592897175633) 
> i don't think all colors are really necessary

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192244669720047657) 
> do you think it'd be reasonable to have the color applicator

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192244868022542417) 
> it doesn't let you dye very many blocks, notably for us it doesn't let you dye concrete powder

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192245256004063232) 
> it's an energy gadget which feels like it's antithetical

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192245699392311297) 
> also we could do something like let the dense cables and/or the non-covered cables be all 16 colors

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192245747932995614) 
> and have those be their own device tier

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192245794259091497) 
> sharing space with the controller

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1192246102456541296) 
> i think that makes sense given the controllers propensity towards being pretty colorful

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192212060705132635/1196391566676340776) 
> for now i made all 16 colors be able to convert to none colored

**Comment by EngineerSmith** [comment]
I don't believe this issue is needed anymore as we're moving to uncoloured with devices. Even the wreck ship will use uncoloured smart cables by #554 

So reopen if needed
