### ISSUE TITLE
Testing discord to github message format

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#467]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192232745032745111/1192232745032745111) 
> Hello, cheese is good because it's made of milk and hard work

**Comment by EngineerSmith** [comment]
Im closing this test... since it isn't needed
