### ISSUE TITLE
Takes too long to load the modpack

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#469]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1192543258329485464/1192543258329485464) 
> When loading the game you get stuck on a white screen for what seems like forever in todays standards. 

Looking at the logs; this is what I found:
```
...
[18:54:53] [modloading-worker-0/INFO] [de.ar.ne.fo.NetworkManagerImpl/]: Registering S2C receiver with id kubejs:toast
Fetching available hotfixes...
404: Not Found can't be hotfixed!
Found 0 hotfixes in 179 ms
[18:56:16] [Render thread/INFO] [quark/]: Dispatching Module Step REGISTER
...
```
As you can see there is a clear 1 minute and ~20 seconds wait time to fetch a 404 page for hotfixes. Track down the mod and fix the issue. If it is the issue.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192543258329485464/1192780169837031495) 
> This is likely related to [Game load freezes](https://discord.com/channels/890222432605057044/1191787237441011894) and we need to report this to modpack update checker

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/677105998674001941/79823e5057cc3b9c05518f7acbc57500.webp" width="15" height="15" center=true/> **jab125** on Discord says](https://discord.com/channels/890222432605057044/1192543258329485464/1194951452095950929) 
> i'd like to say i've fixed the issue now, and it'll be out in the next release

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/677105998674001941/79823e5057cc3b9c05518f7acbc57500.webp" width="15" height="15" center=true/> **jab125** on Discord says](https://discord.com/channels/890222432605057044/1192543258329485464/1194960689513631815) 
> and fixed now in 0.11.2: https://discord.com/channels/1130036219502403655/1133360091018580060/1194960539617607810

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1192543258329485464/1195278851929014302) 
> Thank you! I will update it as soon as I can! You are awesome <:love:1184476584376274995>

**Comment by EngineerSmith** [comment]
This was fixed ^^ loading speed has improved greatly!
