### ISSUE TITLE
[Minor] Wrong toast upon launch about new update available.

### ISSUE THREAD

**Issue by Eweer** [game-design-driven/Create-Prepare-to-Dye#483]
Launcher: Curseforge

Reproducible? Yes.

Showing new update to 1.203.15 available upon launching the game, even though it's already on that version.

Downloaded the pack yesterday (version 1.203.7). Can't remember if I launched it or not. Updated it today to 1.203.15. Toast shows every time I restart the client.

![javaw_uuKzVY9s1b](https://github.com/Yarden-zamir/Create-Prepare-to-Dye/assets/17273593/7773c47d-8aa5-4a9c-8e0d-387d4adea15f)

Green is the current version and yellow is the pending to update one? It might be a curseforge issue then.

![javaw_9LIV5ZZQuL](https://github.com/Yarden-zamir/Create-Prepare-to-Dye/assets/17273593/02a28b94-d6ac-4c68-9ace-a458df52a254)

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/196660908376850433/118a2bcaa316ba6cefbe2c58303ef9d5.webp" width="15" height="15" center=true/> **.eweer** on Discord says](https://discord.com/channels/890222432605057044/1193503855728672808/1193504440267845665) 
> Bot still isn't smart with screenshots.![javaw_uuKzVY9s1b.png](https://cdn.discordapp.com/attachments/1193503855728672808/1193504439705817138/javaw_uuKzVY9s1b.png?ex=65acf4a0&is=659a7fa0&hm=e57b4223aa4757eae5d040867597fca8666514c94f09b46b217727883b324fb9&)![javaw_9LIV5ZZQuL.png](https://cdn.discordapp.com/attachments/1193503855728672808/1193504440007786546/javaw_9LIV5ZZQuL.png?ex=65acf4a0&is=659a7fa0&hm=f47891a3a65a986bf47a299cab1b581c6d7fd701bc693b46b15d7cf2bb339619&)

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193503855728672808/1193505296660840550) 
> Hmm, yea I think it's an issue with. My cf build process

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193503855728672808/1193505499925192704) 
> Beautiful bug report btw thank you

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193503855728672808/1193505598285819956) 
> And yea the discord bot does images from discord to github but not the other way around yet

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1193503855728672808/1193505652170051667) 
> They are actually sperate bots
