### ISSUE TITLE
Cursor jumps when going from p assembler -> inventory -> p assembler

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#494]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1194077236735774761/1194077236735774761) 
> Working on this

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1194077236735774761/1194323686107402370) 
> fixed this

**Comment by Yarden-zamir** [comment]
The fix is merged, I'll close this once we have confirmation that it works

**Comment by EngineerSmith** [comment]
Tested on 1.211.26 and there is no cursor jumping
