### ISSUE TITLE
Crafting Conflict?

### ISSUE THREAD

**Issue by TreyAyy** [game-design-driven/Create-Prepare-to-Dye#498]
I attempted to use the recipe for black dye that shows you can use 1000 mb of black sludge on a slimeball and you apparently get 4 but instead it only put 250 mb for the crafting sequence of silicon. Is this correct and if so could the recipe at least be removed?

**Comment by Yarden-zamir** [comment]
On the latest version?

**Comment by TreyAyy** [comment]
Yes I encountered the issue yesterday I'm pretty sure.

**Comment by TreyAyy** [comment]
Actually I'm so sorry, I just realized curseforge does not automatically
update the pack so I think I'm on version 1.203.14.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1194946311577935936/1195414748125220947) 
> It was indeed a conflict, fixed it the other day though so you should be good now

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1194946311577935936/1195414889229984005) 
> Sidenote for me. Seems that when replaying from email on github the discord message looks like a mess so I need to fix that lol

**Comment by EngineerSmith** [comment]
Fixed. An additional step is required to make silicon now
