### ISSUE TITLE
Add a Zoom Mod

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#513]
[<img src="https://cdn.discordapp.com/avatars/677318114710388737/4f28eda2bec3167f4aa5fbd4a676ee2f.webp" width="15" height="15" center=true/> **Generic name** on Discord says](https://discord.com/channels/890222432605057044/1196381391072526366/1196381391072526366) 
> https://modrinth.com/mod/just-zoom
This might work, it requires Konkrete, but it appears the pack already has that. supports Forge and MC 1.19.2 and other versions

If anyone has a different mod that could work feel free to suggest

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196381391072526366/1196381993370386503) 
> need to change the default key as z is already used by quark but aside form that this mod looks perfect

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/677318114710388737/4f28eda2bec3167f4aa5fbd4a676ee2f.webp" width="15" height="15" center=true/> **Generic name** on Discord says](https://discord.com/channels/890222432605057044/1196381391072526366/1196387412784459818) 
> probably C since thats what optifine uses and probably what most people are used to

**Comment by EngineerSmith** [comment]
(Closing) the Zume mod has been added for zooming; but also uses the z key. Open another issue; or PR if this change is still wanted.
