### ISSUE TITLE
move github projects to org

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#514]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196391059220078665/1196391059220078665) 
> An org will let us have more control over permissinons so contributors can actually close issues and asign them to themselves or eachother. It also makse more sense a it's a comunity project more than it's a Yarden project.
So we need name ideas, my first thought and the permissings experiment that i ran was with the name `game-design-driven`

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196391059220078665/1196391186542383174) 
> [contributors](https://discord.com/channels/890222432605057044/1196391059220078665/1196391186542383174)

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196391059220078665/1196526301767549020) 
> Alright i'm going with game-design-driven as no one intervened to stop me

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1196391059220078665/1196527012425256971) 
> yeah that works!

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196391059220078665/1196530565583740948) 
> I vote for Betsy Club

**Comment by EngineerSmith** [comment]
We've moved to an org now
