### ISSUE TITLE
You can move bedrock with create

### ISSUE THREAD

**Issue by EngineerSmith** [game-design-driven/Create-Prepare-to-Dye#518]
It is possible to move bedrock with the create mod.

I've only tested with rope pully and the create piston and both were able to move the block. 

I hope it is a simple issue that we can just use the block modification kjs event to add the tag `#forge:immovable`

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196546536096669697/1196547596387356682) 
> [pending/contributors/code](https://discord.com/channels/890222432605057044/1196546536096669697/1196547596387356682)

**Comment by Yarden-zamir** [comment]
How did we make the delivery table immovable? I don't see a tag or something

**Comment by Yarden-zamir** [comment]
I see this
```js
        event.modify("wares:delivery_table", block => {
            block.destroySpeed = -1;
            block.explosionResistance = 3600000;
        })
```

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196546536096669697/1199043375689642104) 
> I think it doesn't move because it is a block entity that create doesn't understand

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196546536096669697/1199046923940806747) 
> there must be a way to stop it though
