### ISSUE TITLE
Extend reach for GUI

### ISSUE THREAD

**Issue by EngineerSmith** [game-design-driven/Create-Prepare-to-Dye#520]
Currently when you try to open some inventories you get an issue of flashing off when you try to open it. This can be fixed by using Mixin in Ptdyeplus.

Right now vanilla containers can be reached; but this needs to be extended to all interfaces now.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1196891626040205512) 
> Hm..

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1196891868013789336) 
> We dont have many guis lol, nothing else comes to mind

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1196891953342718092) 
> Thats a good sign

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1196891968266047600) 
> I'll just make sure all vanilla stuff work at least. Brewing stands, etc.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1196892233186676786) 
> Yes, although a lot of them are removed or will be its probably better to have them all fixed

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1197197119124164678) 
> I tried to extend the reach to the stone cutter (as a block). and I just get crashes. So I'll leave it with what I've got so far and make a PR to ptdyeplus.

**Comment by EngineerSmith** [comment]
https://github.com/jasperalani/ptdye-plus/pull/6

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1197460508744364062) 
> thats ok i want to remove the stonecutter anyway.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199527233518305351) 
> [engineersmith_4628](https://discord.com/channels/890222432605057044/1196881775260078120/1199527233518305351) is there a reason why you don't just mix into a shared parent?

(`BaseContainerBlockEntity`, `WorldlyContainer`, or `Container` for most, though you'd probably want one of the latter two)

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199643626217676831) 
> because the ones that I did change override the functions within those

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199643725542981653) 
> and don't call super

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199643775836897352) 
> oopsies

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199643840919896095) 
> It's all good ^^ important to ask these questions for code review

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199644288133382274) 
> if you feel comfortable enough with more annoying mixins then try taking a look at [#12](https://github.com/game-design-driven/ptdye-plus/pull/12). [Feature request: Make it free to rename things in the anvil](https://discord.com/channels/890222432605057044/1193510842638024865) turns out to just be way easier in a mixin but it wasn't quite working as anticpated. I'm going to take another look tmrw but I have the idea down (I think) the execution just needs to be corrected

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199644640891129856) 
> Since while I understand mixin (mostly) I haven't done it alot, if you have more expierence it might be a better task for you.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199645330799611965) 
> oh lol. No worries then since I plan on working on it later anyway

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199645696274473010) 
> 👀 not to nit pick, but could you move this line down one so it's still alphabetical
https://github.com/CoolandonRS/ptdye-plus/commit/9e08ec17847010666fc0276e8ee9c007420b4e84#diff-1a9720718d14c6295fc1134db3b40778a164277b2084cea9aa8835d55318e844R8

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1196881775260078120/1199645848615784488) 
> Oh yeah. I did it that way to organize by purpose, but alphabetical might make more sense.

**Comment by EngineerSmith** [comment]
Implemented
