### ISSUE TITLE
make bedrock unmoveable

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#523]

**Comment by EngineerSmith** [comment]
#518 this issue already exists

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1197586187087515789/1198047174571864164) 
> bedrock is meant to be Unmovable according to the wiki: https://create.fandom.com/wiki/Contraption

**Comment by Yarden-zamir** [comment]
Oh woops, closing as duplicate then.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1197586187087515789/1198329748850479255) 
> https://discord.com/channels/890222432605057044/1196546536096669697/1196547596387356682
