### ISSUE TITLE
Train Schedules and Conductors.

### ISSUE THREAD

**Issue by TreyAyy** [game-design-driven/Create-Prepare-to-Dye#526]
I'm experiencing an issue where I cannot apply the train schedule I made to a mob/conductor. My train is assembled, seat in front of the controls, but every time I click the mob it just pulls up the train schedule.

EDIT: This time I made sure to update to the latest version available.

**Comment by TreyAyy** [comment]
Has anyone else experienced this issue? I have stopped playing the pack altogether until I figure it out.

**Comment by Yarden-zamir** [comment]
no, and people made working trains. am not exactly sure what you are encountering here.

**Comment by Yarden-zamir** [comment]
are you sure the mob is seated?

**Comment by Yarden-zamir** [comment]
can you try to use a blaze burner? I think those work too

**Comment by TreyAyy** [comment]
And yes I did everything right. I even switched to a different pack to make sure I was doing the right thing.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1197640900256473128/1198569281026265120) 
> hmm what animal did you use?

**Comment by TreyAyy** [comment]
I've figured out the issue I think, I might not have had the seat superglued to the train for some reason. I thought I did but I guess not.

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1197640900256473128/1199221014211592212) 
> <:thumbsup:1191476503750397982>
