### ISSUE TITLE
Create documentation for all of the kubejs binded functions

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#537]
[<img src="https://cdn.discordapp.com/avatars/145122297257132032/9b7bfe09029ad9f0e8dc639015ae8838.webp" width="15" height="15" center=true/> **kikis2111** on Discord says](https://discord.com/channels/890222432605057044/1199307804280901712/1199307804280901712) 
> It can be added in the middle of the readme.
Think just the functions in ```CellUtilJS.java``` and ```KeyUtilJS.java```. and possibly the public functions in ```appeng``` package
[coolandonrs](https://discord.com/channels/890222432605057044/1199307804280901712/1199307804280901712) ill do key util when 

https://github.com/jasperalani/ptdye-plus/issues/9

**Comment by jasperalani** [comment]
not intended for this repo
