### ISSUE TITLE
Mod: Fluidlogged

### ISSUE THREAD

**Issue by EngineerSmith** [game-design-driven/Create-Prepare-to-Dye#556]
Add the following mod, forge 1.19.2
https://modrinth.com/mod/fluidlogged
https://www.curseforge.com/minecraft/mc-mods/fluidlogged

Imagine water logged blocks but milk and other fluids.
![image](https://github.com/game-design-driven/Create-Prepare-to-Dye/assets/56016593/e985349b-ca6b-4f4b-9238-be0624380430)

### Notes
I tried adding it in - but hit a wall with multiplayer. Not sure what's going wrong; just wouldn't let me login to the server. Probably better to wait till the recent PRs to add multiplayer fixes are pulled into the main stream

### Config file
[config/fluidlogged.json](https://github.com/game-design-driven/Create-Prepare-to-Dye/files/14070286/fluidlogged.json)
It seems very, **very**, **_very_** delicate about the config. So updating it to add additional fluids may break worlds in the future (in terms of fluids suddenly becoming other fluids in fluid logged blocks).

**Comment by Yarden-zamir** [comment]
that sounds scary

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1200594579141967902/1201599110701129869) 
> evvvil mod

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1200594579141967902/1201599155198513234) 
> wishes your save nothing but harm

**Comment by Yarden-zamir** [comment]
I'm not too keen on adding something that has this destructive potential

**Comment by EngineerSmith** [comment]
I agree - so I'm closing this

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1200594579141967902/1202287066881204274) 
> 👍
