### ISSUE TITLE
Raw white can't be made on a depot or belt

### ISSUE THREAD

**Issue by Auseawesome** [game-design-driven/Create-Prepare-to-Dye#589]
A deploying recipe should be added alongside the in world interaction to make automation less frustrating

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210265942462963792) 
> [auseawesome](https://discord.com/channels/890222432605057044/1210265768487428158/1210265942462963792) what are you finding frustrating about it? just feed it into a deployer

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266005553807381) 
> you have to physically place the dust down

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266032707608706) 
> deployers can do that

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266054647873616) 
> that's intentional

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266162701537390) 
> is it? Because that way causes more lag due to entities on the ground as its dropped and makes automation a lot more difficult

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266167663525978) 
> it's to make it more complex as a process

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266250471673897) 
> it isn't more complex really it's just more irritating, because I could just stick the deployers on the top of my pure daisies

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266255794118697) 
> it's an entity that can be nearly insantly picked up by a chute/hopper

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266377890562068) 
> i guess? i use part of my white powder production for dye though

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266399356751903) 
> so that wouldn't work great for me

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266463118823514) 
> that's the exact issue

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266547302694933) 
> It's really annoying for compact setups

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266577208086588) 
> and makes it much easier just to manually do it

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266702600872048) 
> it's a pretty boring process so i just set up some deployers

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266719466168330) 
> I have white powder fully automated

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266749245726800) 
> its the raw white thats really easy to manually do

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266759412846684) 
> wait

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266764944867338) 
> raw white

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266770884272158) 
> i mean

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266774516535366) 
> sorry

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266817235525752) 
> it still takes time you could use for other things

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266858310078484) 
> it takes like 10 seconds to do a whole stack

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266941504094228) 
> why would you spend 10 seconds doing something manually

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266968213426228) 
> when you could automate it in 10 minutes

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210266990577717248) 
> because automating is a giant nightmare

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267077793939496) 
> if automation is a nightmare then the pack is kind of not going to be a good experience for you

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267078230155285) 
> because you have to place it down, setup a collection system for the items which have a habit of jumping around when placed down

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267129816027236) 
> 🤦🏼‍♂️

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267141102632961) 
> that's not what I meant

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267152494362684) 
> a basic hopper is enough of a "collection system"

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267174539890780) 
> I've played the entirety of create above and beyond

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267275530338335) 
> not for raw white, at high speeds the deployer places the next block down before the hopper picks it up which can launch the raw white out of the space

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267352805941301) 
> i guess just clock it down then

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267373513474110) 
> high speeds break lots of setups

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267442098471033) 
> having to clock down your entire power system just because you can't deploy onto a belt seems absurd

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267478349979688) 
> it's not like being able to deploy onto a belt breaks existing setups

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267591646515220) 
> at least in your case

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267635804143686) 
> also it's not your *entire* power system

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267668477648946) 
> it's just your white powder area

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267719119667240) 
> its hooked into my entire power with no easy way to clock it down

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267737218093148) 
> due to it being a compact setup

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267761776009246) 
> really i keep everything around 64rpm tops personally

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267805044445204) 
> I got a bunch at 256 rpm

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210267915237072986) 
> also create makes all existing in world interactions available through deployers

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268048616071240) 
> in-world processes add more logistical complexity which you have to reason through

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268120741183508) 
> not really?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268192002277487) 
> that's not an issue with the belt method

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268220855025684) 
> ergo, requires less thought

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268240178319427) 
> that just gets frustrating in my experience

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268276152737833) 
> rather than actually making for a fun challenge

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268299900883035) 
> especially when redstone isnt properly implemented

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268318381121653) 
> its a logistical nightmare

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268369719271526) 
> and you were saying about some stuff ruining compact setups and why it shouldnt be changed

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268378715922484) 
> oh yeah i forgot the redstone issue

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268405425377320) 
> this is a prime example of ruining compact setups

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268420382400553) 
> its a giant pain

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268499331645470) 
> and not being able to automate raw white properly until redstone is stupid

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268573961027704) 
> at least just make it an option to add it so people can choose

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268595897245696) 
> the pack is modular after all

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268735840194592) 
> you can add a feature called "disable on-belt raw white production" i guess

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268786284961843) 
> why not 'enable'

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268835186217001) 
> because features default to true

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268871668531200) 
> that's the logic of them

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268873337610380) 
> not if you set them to default to false

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268945932623902) 
> you can just go in the features json file

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268956565180496) 
> and change it to false

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268957588848660) 
> oh yeah there is behavior for that

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268981123096636) 
> but also it'd be best to not do that

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210268995467345940) 
> why?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269016246198282) 
> in case we decide to re-generate the features.json file

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269048680742962) 
> or someone has an older version of it

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269087628927046) 
> and updates the pack

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269147074920499) 
> i'm pretty sure it's easy to make a default false feature

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269167115182100) 
> it is

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269241190916187) 
> directly modifying the features.json is NOT how to do it though

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269475383939122) 
> it should be .gitignored yeah

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269496120582155) 
> i don't know why it isn't

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269497110560818) 
> I shall do that now

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210269514537893908) 
> at the same time

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210272695976206406) 
> nevermind ignore me I found it

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210275164500262913) 
> not properly checking for null etc

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210275175568773180) 
> going to have to fix them

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210275988215169105) 
> Found the issue

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210280082804051998) 
> [autistic.sack.of.friends](https://discord.com/channels/890222432605057044/1210265768487428158/1210280082804051998) https://github.com/game-design-driven/Create-Prepare-to-Dye/pull/590, critical fix

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/635733552457187360/9d95a6c645aef01ff030b0788aceb65c.webp" width="15" height="15" center=true/> **auseawesome** on Discord says](https://discord.com/channels/890222432605057044/1210265768487428158/1210280119021731873) 
> and also closes this issue
