### ISSUE TITLE
ender dragon respawn

### ISSUE THREAD

**Issue by Yarden-zamir** [game-design-driven/Create-Prepare-to-Dye#593]

**Comment by Yarden-zamir** [comment]
Woops

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/677318114710388737/4f28eda2bec3167f4aa5fbd4a676ee2f.webp" width="15" height="15" center=true/> **genericname0144** on Discord says](https://discord.com/channels/890222432605057044/1219352857137123370/1219362699981488188) 
> no large omlete factory qwq
