### ISSUE TITLE
iron golems can drop iron ingots

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#595]
[<img src="https://cdn.discordapp.com/avatars/677318114710388737/4f28eda2bec3167f4aa5fbd4a676ee2f.webp" width="15" height="15" center=true/> **genericname0144** on Discord says](https://discord.com/channels/890222432605057044/1223557475739897907/1223557475739897907) 
> obvious title is obvious

**Comment by Yarden-zamir** [comment]
I expect this should be enough, but can't test it. If someone can give it a go and tell me if its good that'l be great
```js
# loot.js
if (feature('Replace white ingot (iron ingot) with iron plates')) {
  LootJS.modifiers((event) => {
    event
      .addEntityLootModifier("minecraft:iron_golem")
      .replaceLoot("minecraft:iron_ingot", "create:iron_sheet")
  }); 
}
```
