### ISSUE TITLE
testing if bot is alive discord to github

### ISSUE THREAD

**Issue by Discord-Github-Bridge** [game-design-driven/Create-Prepare-to-Dye#607]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1294941585129078824/1294941585129078824) 
> a

**Comment by Yarden-zamir** [comment]
comment on github
