### ISSUE TITLE
KubeJS Scripts do not work on the server

### ISSUE THREAD

**Issue by JulianVennen** [game-design-driven/Create-Prepare-to-Dye#620]
When you try to run a server with version 1.222.3 the server crashes because a KubeJS script tries to access client only classes.
Server log: https://mclo.gs/HjuLLQa#L606
KubeJS log: https://mclo.gs/mlJn4AU

**Comment by Yarden-zamir** [comment]
Oh no, that's not great, fixing

**Comment by Yarden-zamir** [comment]
Fixed

**Comment by Yarden-zamir** [comment]
@JulianVennen Thanks for the report!
